Algoritmo "exercicio de idades- se , senao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/03/2025
Var
// Seção de Declarações das variáveis 
idade: inteiro
nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("informe seu nome")
leia (nome)
escreva("informe sua idade:")
leia (idade)

se ( idade <= 12 ) entao
   escreva("voce ainda e uma crianca")
senao
   se ( idade >= 13) e (idade <= 17) entao
     escreva ("voce e um aborecente")
senao
     se (idade >= 18) e (idade <= 59) entao
        escreva ("voce e um adulto responsavel")
senao
      se ( idade >= 60)e (idade <= 100)  entao
         escreva ("voce e um idoso muito fofinho")
senao
    escreva ("voce e imortal")
    
      fimse
     fimse
  fimse
fimse                                                                                                                                                                                      cucucucucucu  cucucucucucucucucucucucucucucucucucucucucucucucucucucuccucucucucucu  cucucucucucucucucucucucucucucucucucucucucucucucucucucuccucucucucucu  cucucucucucucucucucucucucucucucucucucucucucucucucucucuc
Fimalgoritmo